# Site settings
title: Aerol.github.io
email: rectifier04@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, rants and data smorgasbord <br />from a Mad Scientest.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aerol.github.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Aerol

# Build settings
markdown: kramdown
